### ISSUE TITLE
panic when diagnose connection to service

### ISSUE THREAD

**Issue by qdyyyy** [alibaba/kubeskoop#62]
### Environment Info
kubernetes: v1.25.0
calico: v3.24.1
skoop: latest

### Issue Description
```shell
[root@sealos-k8s-master kubeskoop]# kubectl get svc -n kubeskoop
NAME                 TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE
grafana              NodePort    10.96.2.143   <none>        80:32194/TCP   20h
loki-service         ClusterIP   10.96.2.157   <none>        3100/TCP       20h
prometheus-service   NodePort    10.96.0.75    <none>        80:30758/TCP   20h
[root@sealos-k8s-master kubeskoop]# skoop -s 192.168.43.134 -d 10.96.0.75 -p 80 --format json --output b.json -v=5 --calico-host-interface=ens33
I0707 14:59:55.540284  289291 cluster.go:84] Detected network plugin "calico".
I0707 14:59:55.542818  289291 cluster.go:99] Detected kube-proxy mode "ipvs"
I0707 14:59:55.545606  289291 cluster.go:118] Detected cluster cidr "100.64.0.0/10"
I0707 14:59:55.559855  289291 ip_cache.go:216] Pod calico-system/calico-node-8zsct skipped, hostNetwork: true, phase: Running
I0707 14:59:55.559903  289291 ip_cache.go:216] Pod calico-system/calico-typha-8df7945c6-rjk94 skipped, hostNetwork: true, phase: Running
I0707 14:59:55.559947  289291 ip_cache.go:216] Pod kube-system/etcd-sealos-k8s-master skipped, hostNetwork: true, phase: Running
I0707 14:59:55.559965  289291 ip_cache.go:216] Pod kube-system/kube-apiserver-sealos-k8s-master skipped, hostNetwork: true, phase: Running
I0707 14:59:55.559969  289291 ip_cache.go:216] Pod kube-system/kube-controller-manager-sealos-k8s-master skipped, hostNetwork: true, phase: Running
I0707 14:59:55.559972  289291 ip_cache.go:216] Pod kube-system/kube-proxy-2gp9l skipped, hostNetwork: true, phase: Running
I0707 14:59:55.559975  289291 ip_cache.go:216] Pod kube-system/kube-scheduler-sealos-k8s-master skipped, hostNetwork: true, phase: Running
I0707 14:59:55.559978  289291 ip_cache.go:216] Pod kube-system/metrics-server-55c774cdbb-jvmth skipped, hostNetwork: false, phase: Pending
I0707 14:59:55.560002  289291 ip_cache.go:216] Pod kubeskoop/kubeskoop-exporter-62kd8 skipped, hostNetwork: true, phase: Running
I0707 14:59:55.560030  289291 ip_cache.go:216] Pod tigera-operator/tigera-operator-6675dc47f4-xzdmv skipped, hostNetwork: true, phase: Running
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1b0 pc=0x1cee798]

goroutine 1 [running]:
github.com/alibaba/kubeskoop/pkg/skoop/service.isExternalTraffic(0xc0005eb400, 0x0, {{0xc0003e6440, 0x10, 0x10}, 0x0, {0xc0003e6450, 0x10, 0x10}, 0x50, ...})
        /root/go/pkg/mod/github.com/alibaba/kubeskoop@v0.0.2-alpha/pkg/skoop/service/service.go:192 +0x78
github.com/alibaba/kubeskoop/pkg/skoop/service.(*KubeProxyServiceProcessor).Process(0xc00011cf40, {{0xc0003e6440, 0x10, 0x10}, 0x0, {0xc0003e6450, 0x10, 0x10}, 0x50, {0x264d159, ...}, ...}, ...)
        /root/go/pkg/mod/github.com/alibaba/kubeskoop@v0.0.2-alpha/pkg/skoop/service/service.go:166 +0x128
github.com/alibaba/kubeskoop/pkg/skoop/plugin.(*networkPolicy).CheckNetworkPolicy(0xc0005f8180, {{0x7ffd14b76cd0, 0xe}, {0x264da7e, 0x4}, 0x0}, {{0x7ffd14b76ce2, 0xa}, {0x265182d, 0x7}, ...}, ...)
        /root/go/pkg/mod/github.com/alibaba/kubeskoop@v0.0.2-alpha/pkg/skoop/plugin/networkpolicy.go:88 +0x942
github.com/alibaba/kubeskoop/pkg/skoop/skoop.(*defaultDiagnostor).diagnoseNetworkPolicy(0x800?, {{0x7ffd14b76cd0, 0xe}, {0x264da7e, 0x4}, 0x0}, {{0x7ffd14b76ce2, 0xa}, {0x265182d, 0x7}, ...}, ...)
        /root/go/pkg/mod/github.com/alibaba/kubeskoop@v0.0.2-alpha/pkg/skoop/skoop/diagnose.go:60 +0xa6
github.com/alibaba/kubeskoop/pkg/skoop/skoop.(*defaultDiagnostor).Diagnose(0xc0003ea480, {{0x7ffd14b76cd0, 0xe}, {0x264da7e, 0x4}, 0x0}, {{0x7ffd14b76ce2, 0xa}, {0x265182d, 0x7}, ...}, ...)
        /root/go/pkg/mod/github.com/alibaba/kubeskoop@v0.0.2-alpha/pkg/skoop/skoop/diagnose.go:69 +0xb5
github.com/alibaba/kubeskoop/pkg/skoop/network/generic.(*calicoNetwork).Diagnose(0xc00004fd40, 0x0?, {{0x7ffd14b76cd0, 0xe}, {0x264da7e, 0x4}, 0x0}, {{0x7ffd14b76ce2, 0xa}, {0x265182d, ...}, ...})
        /root/go/pkg/mod/github.com/alibaba/kubeskoop@v0.0.2-alpha/pkg/skoop/network/generic/network.go:34 +0xe3
github.com/alibaba/kubeskoop/pkg/skoop/cmd.NewSkoopCmd.func2(0xc000300900?, {0x264d936?, 0xc?, 0xc?})
        /root/go/pkg/mod/github.com/alibaba/kubeskoop@v0.0.2-alpha/pkg/skoop/cmd/app.go:43 +0x328
github.com/spf13/cobra.(*Command).execute(0xc000300900, {0xc000040420, 0xc, 0xc})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000300900)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0xc000006340?)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968 +0x19
main.main()
        /root/go/pkg/mod/github.com/alibaba/kubeskoop@v0.0.2-alpha/cmd/skoop/main.go:10 +0x25
```

**Comment by Lyt99** [comment]
This is a known issue, someone is taking this issue and should be fixed in a few days.
